export default {
    GET_SHIPPING_ONLINE: '[SHIPPING] GET_SHIPPING_ONLINE',
    GET_LIST_SHIPPING: '[SHIPPING] GET_LIST_SHIPPING',
    GET_LIST_SHIPPING_RESULT: '[SHIPPING] GET_LIST_SHIPPING_RESULT',
    POPUP_TYPE_SHIPPING: '[SHIPPING] POPUP',
    POPUP_TYPE_SHIPPING_ADDRESS: '[SHIPPING] POPUP_ADDRESS',
    GET_SHIPPING_METHODS: '[SHIPPING] GET_SHIPPING_METHODS',
    SAVE_SHIPPING: "[SHIPPING] SAVE_SHIPPING",
    SAVE_SHIPPING_AFTER: "[SHIPPING] SAVE_SHIPPING_AFTER"
}