export default {
    POPUP_TYPE_STAFF_DISCOUNT: '[STAFF DISCOUNT] POPUP',
    POPUP_TYPE_STAFF_MANAGER_PINCODE: '[STAFF DISCOUNT] STAFF MANAGER PINCODE POPUP',
    POPUP_TYPE_STAFF_MANAGER_DISCOUNT: '[STAFF DISCOUNT] POPUP TYPE STAFF MANAGER DISCOUNT',
    CHECK_MANAGER_PINCODE: '[STAFF DISCOUNT] CHECK MANAGER PINCODE',
    RESET_CHECK_MANAGER_PINCODE: '[STAFF DISCOUNT] RESET CHECK MANAGER PINCODE',
    CHECK_MANAGER_PINCODE_RESULT: '[STAFF DISCOUNT] CHECK MANAGER PINCODE RESULT',
    CHECK_MANAGER_PINCODE_ERROR: '[STAFF DISCOUNT] CHECK MANAGER PINCODE ERROR'
}